In [12]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [13]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [14]:
## Define the vocabulary size
voc_size=10000

In [15]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5817, 2740, 6543, 6860],
 [5817, 2740, 6543, 8935],
 [5817, 3470, 6543, 3023],
 [6472, 6552, 9052, 5069, 8425],
 [6472, 6552, 9052, 5069, 1880],
 [4097, 5817, 4203, 6543, 7419],
 [3814, 8604, 2414, 5069]]

In [16]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5817 2740 6543 6860]
 [   0    0    0    0 5817 2740 6543 8935]
 [   0    0    0    0 5817 3470 6543 3023]
 [   0    0    0 6472 6552 9052 5069 8425]
 [   0    0    0 6472 6552 9052 5069 1880]
 [   0    0    0 4097 5817 4203 6543 7419]
 [   0    0    0    0 3814 8604 2414 5069]]


In [17]:
## feature representation
dim=10

In [18]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [19]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [20]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 180ms/step


array([[[-1.3913237e-02,  3.5617914e-02, -5.4303035e-03, -4.1742671e-02,
          9.8866113e-03,  1.8882047e-02,  3.1057484e-03, -3.7551749e-02,
          1.2407243e-02, -4.0548254e-02],
        [-1.3913237e-02,  3.5617914e-02, -5.4303035e-03, -4.1742671e-02,
          9.8866113e-03,  1.8882047e-02,  3.1057484e-03, -3.7551749e-02,
          1.2407243e-02, -4.0548254e-02],
        [-1.3913237e-02,  3.5617914e-02, -5.4303035e-03, -4.1742671e-02,
          9.8866113e-03,  1.8882047e-02,  3.1057484e-03, -3.7551749e-02,
          1.2407243e-02, -4.0548254e-02],
        [-1.3913237e-02,  3.5617914e-02, -5.4303035e-03, -4.1742671e-02,
          9.8866113e-03,  1.8882047e-02,  3.1057484e-03, -3.7551749e-02,
          1.2407243e-02, -4.0548254e-02],
        [-3.8881719e-02, -3.9771546e-02,  3.1707857e-02, -4.6039939e-02,
          3.9423931e-02,  6.4963922e-03, -2.6957858e-02,  4.8141804e-02,
         -2.4410337e-04, -2.5745153e-02],
        [ 2.1243643e-02,  1.2835059e-02, -1.3604093e-02, -7.

In [21]:
embedded_docs[0]

array([   0,    0,    0,    0, 5817, 2740, 6543, 6860])

In [22]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 72ms/step


array([[-0.01391324,  0.03561791, -0.0054303 , -0.04174267,  0.00988661,
         0.01888205,  0.00310575, -0.03755175,  0.01240724, -0.04054825],
       [-0.01391324,  0.03561791, -0.0054303 , -0.04174267,  0.00988661,
         0.01888205,  0.00310575, -0.03755175,  0.01240724, -0.04054825],
       [-0.01391324,  0.03561791, -0.0054303 , -0.04174267,  0.00988661,
         0.01888205,  0.00310575, -0.03755175,  0.01240724, -0.04054825],
       [-0.01391324,  0.03561791, -0.0054303 , -0.04174267,  0.00988661,
         0.01888205,  0.00310575, -0.03755175,  0.01240724, -0.04054825],
       [-0.03888172, -0.03977155,  0.03170786, -0.04603994,  0.03942393,
         0.00649639, -0.02695786,  0.0481418 , -0.0002441 , -0.02574515],
       [ 0.02124364,  0.01283506, -0.01360409, -0.00701797,  0.02235674,
         0.04761919,  0.01553892, -0.04455635,  0.04248368, -0.02866885],
       [-0.02522355,  0.00986544, -0.01993291, -0.0147871 , -0.02097832,
         0.01637972, -0.0401901 , -0.04482638